import json
from pathlib import Path

def greenhouse_component(values, core):
    root=Path(__file__).parent/'viewer-assets'
    planting=(root/'planting.js').read_text(encoding='utf-8').split('\n')[0].replace('export ','')
    equipment=(root/'equipment.js').read_text(encoding='utf-8').replace('export ','')
    viewer='\n'.join(line for line in (root/'viewer.js').read_text(encoding='utf-8').splitlines() if not line.startswith('import ')).replace('export ','')
    s=dict(width=values['gh_width'],length=values['gh_length'],side=values['gh_side_h'],ridge=values['gh_ridge_h'],spans=values['span_count'],rowSpacing=2,plantSpacing=1,month=6,wind=core.side_wing_factor(values['side_wing_level'],values['side_wing_width']),windWidth=values['side_wing_width'])
    return '''<!doctype html><html lang="ko"><head><meta charset="utf-8"><style>body{margin:0;font:12px sans-serif;color:#173541}#toolbar{display:flex;gap:6px;padding:8px;background:#f1f5f6;flex-wrap:wrap}button{padding:7px 12px;background:white;border:1px solid #d4e0e4;border-radius:4px;cursor:pointer}#viewer{height:340px;position:relative;overflow:hidden}.viewer-note{position:absolute;bottom:8px;left:8px;background:#ffffffe6;padding:6px;font-size:10px}canvas{display:block}</style><script type="importmap">{"imports":{"three":"https://unpkg.com/three@0.169.0/build/three.module.js","three/addons/":"https://unpkg.com/three@0.169.0/examples/jsm/"}}</script></head><body><div id="toolbar"><button data-view="perspective">사선</button><button data-view="front">정면</button><button data-view="side">측면</button><button data-view="top">평면</button><button data-view="equipment">양액설비</button><button data-mode="outside">외부</button><button data-mode="inside">내부</button><button data-mode="frame">골조</button></div><div id="viewer">3D 준비 중…</div><script type="module">'''+planting+'\n'+equipment+'\n'+viewer+'\nconst state='+json.dumps(s)+''';let view='perspective',mode='outside',dispose=()=>{},generation=0;async function render(){dispose();const token=++generation;const fn=await mountViewer(document.getElementById('viewer'),state,{view,mode,equipment:true,curtain:'open',filmVisible:true});if(token===generation)dispose=fn;else fn()}document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;render()});render();</script></body></html>'''
