import {addEquipment} from './equipment.js';
import {plantingLayout} from './planting.js';
export async function mountViewer(holder,s,{view='perspective',mode='outside',equipment=true,curtain='open',filmVisible=true}={}){
 let disposed=false,renderer,frame,observer,controls,scene;
 const dispose=()=>{disposed=true;cancelAnimationFrame(frame);observer?.disconnect();controls?.dispose();if(scene){scene.traverse(o=>{o.geometry?.dispose();if(o.material)(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>(m.map?.dispose(),m.dispose()))})}renderer?.dispose();renderer?.domElement.remove()};
 try{let timeout;const [THREE,{OrbitControls}]=await Promise.race([Promise.all([import('three'),import('three/addons/controls/OrbitControls.js')]).finally(()=>clearTimeout(timeout)),new Promise((_,reject)=>{timeout=setTimeout(()=>reject(Error('3D library loading timed out')),15000)})]);if(!holder.isConnected)return dispose;scene=new THREE.Scene();scene.background=new THREE.Color(0xeaf0f5);scene.fog=new THREE.Fog(0xdcebef,140,300);const camera=new THREE.PerspectiveCamera(40,1,.1,500);renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;holder.replaceChildren(renderer.domElement);controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.maxPolarAngle=Math.PI*.49;scene.add(new THREE.HemisphereLight(0xffffff,0x66775e,2.5));const sun=new THREE.DirectionalLight(0xfff3db,3);sun.position.set(-30,45,25);scene.add(sun);const steel=new THREE.MeshStandardMaterial({color:0xa8b9b7,metalness:.8,roughness:.3}),film=new THREE.MeshPhysicalMaterial({color:0xe4f1e9,transparent:true,opacity:mode==='inside'?.09:.32,side:THREE.DoubleSide,depthWrite:false,roughness:.3}),soil=new THREE.MeshStandardMaterial({color:0x8a8270}),leaf=new THREE.MeshStandardMaterial({color:0x4e725c}),trunk=new THREE.MeshStandardMaterial({color:0x816347}),fruit=new THREE.MeshStandardMaterial({color:s.month>=9?0x8c4974:0x88a849});
 const ground=new THREE.Mesh(new THREE.PlaneGeometry(400,400),new THREE.MeshStandardMaterial({color:0xd5dfdf}));ground.rotation.x=-Math.PI/2;scene.add(ground);const grid=new THREE.GridHelper(200,100,0x93a9b5,0xc2cfd6);grid.position.y=.015;scene.add(grid);const W=s.width*s.spans,L=s.length,H=s.ridge,n=Math.ceil(L/3),group=new THREE.Group();scene.add(group);
 function tube(a,b,r=.03,mat=steel){const d=new THREE.Vector3().subVectors(b,a),m=new THREE.Mesh(new THREE.CylinderGeometry(r,r,d.length(),6),mat);m.position.copy(a).add(b).multiplyScalar(.5);m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),d.normalize());group.add(m)}
 function arc(x,k,z){const t=k/16*Math.PI;return new THREE.Vector3(x+s.width/2-s.width/2*Math.cos(t),s.side+(H-s.side)*Math.sin(t),z)}
 for(let q=0;q<s.spans;q++){const x=-W/2+q*s.width;for(let j=0;j<=n;j++){const z=-L/2+j*L/n;tube(new THREE.Vector3(x,0,z),new THREE.Vector3(x,s.side,z),.045);tube(new THREE.Vector3(x+s.width,0,z),new THREE.Vector3(x+s.width,s.side,z),.045);for(let k=0;k<16;k++)tube(arc(x,k,z),arc(x,k+1,z))}for(let k=0;k<=16;k+=2)tube(arc(x,k,-L/2),arc(x,k,L/2),.025);if(mode!=='frame'&&filmVisible){const verts=[];for(let k=0;k<16;k++){const a=arc(x,k,-L/2),b=arc(x,k+1,-L/2),c=arc(x,k,L/2),d=arc(x,k+1,L/2);[a,b,c,b,d,c].forEach(p=>verts.push(p.x,p.y,p.z))}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(verts,3));geo.computeVertexNormals();group.add(new THREE.Mesh(geo,film));for(const z of [-L/2,L/2]){const end=new THREE.Mesh(new THREE.PlaneGeometry(s.width,s.side),film);end.position.set(x+s.width/2,s.side/2,z);group.add(end)}}}
 if(mode!=='frame'){const layout=plantingLayout(s),rows=layout.rows,plants=layout.plantsPerRow,stride=Math.max(1,Math.ceil(layout.total/450));const leafGeo=new THREE.SphereGeometry(.25,7,5),fruitGeo=new THREE.SphereGeometry(.09,6,4),crateMat=new THREE.MeshStandardMaterial({color:0x286957,roughness:.75}),crateLong=new THREE.BoxGeometry(.6,.32,.035),crateShort=new THREE.BoxGeometry(.035,.32,.4),substrate=new THREE.BoxGeometry(.55,.06,.35);for(let q=0;q<s.spans;q++)for(let row=0;row<rows;row++){const x=layout.rowX(q,row);tube(new THREE.Vector3(x,2.15,-L/2),new THREE.Vector3(x,2.15,L/2),.012);for(let p=0;p<plants;p+=stride){const z=layout.plantZ(p);if(equipment&&z<-L/2+2.4*Math.min(1,W/7,s.side/2.5,L/8))continue;const growth=s.month<=2?.35:s.month===3?.6:1;for(const dir of [-1,1]){const long=new THREE.Mesh(crateLong,crateMat);long.position.set(x,.2,z+dir*.2);group.add(long);const short=new THREE.Mesh(crateShort,crateMat);short.position.set(x+dir*.3,.2,z);group.add(short)}const fill=new THREE.Mesh(substrate,soil);fill.position.set(x,.24,z);group.add(fill);tube(new THREE.Vector3(x,.27,z),new THREE.Vector3(x,1.6*growth,z),.025,trunk);if(s.month>2){for(const dir of [-1,1]){tube(new THREE.Vector3(x,.8*growth,z),new THREE.Vector3(x+dir*.35,1.25*growth,z),.014,trunk);for(let k=0;k<2;k++){const mesh=new THREE.Mesh(leafGeo,leaf);mesh.scale.set(1.15,.25,1);mesh.position.set(x+dir*(.2+k*.15),(1.0+k*.22)*growth,z);group.add(mesh)}}if(s.month>=6){const f=new THREE.Mesh(fruitGeo,fruit);f.position.set(x+.17,.95,z);group.add(f)}}}}if(s.wind<1&&s.windWidth>0)for(const d of s.wind===.97?[-1]:[-1,1]){const wall=new THREE.Mesh(new THREE.PlaneGeometry(L,s.windWidth),new THREE.MeshStandardMaterial({color:0x739789,transparent:true,opacity:.6,side:THREE.DoubleSide}));wall.rotation.y=Math.PI/2;wall.position.set(d*(W/2+1),s.windWidth/2,0);group.add(wall)}}
 addEquipment(THREE,group,s,{equipment,curtain});
 const dist=Math.max(W*1.8,L*1.15,H*6);camera.position.set(view==='front'?0:view==='side'?dist:view==='top'?.01:dist*.65,view==='top'?dist:mode==='inside'?s.side*.65:dist*.4,view==='front'?-dist:view==='side'?0:view==='top'?.01:mode==='inside'?-L*.35:-dist*.8);if(mode==='inside'&&view==='perspective')camera.position.x=-W/2+s.width*.5;controls.target.set(0,H*.4,0);if(view==='equipment'){const k=Math.min(1,W/7,s.side/2.5,L/8);camera.position.set(4*k,3.2*k,-L/2+7*k);controls.target.set(0,1*k,-L/2+1.2*k)}controls.update();observer=new ResizeObserver(()=>{renderer.setSize(holder.clientWidth,holder.clientHeight,false);camera.aspect=holder.clientWidth/holder.clientHeight;camera.updateProjectionMatrix()});observer.observe(holder);function animate(){if(disposed)return;frame=requestAnimationFrame(animate);controls.update();renderer.render(scene,camera)}animate();const note=document.createElement('div');note.className='viewer-note';note.textContent='드래그 회전 · 휠 확대 · 우클릭 이동 | 설비·작물은 개략 모델 · 커튼은 천장형';holder.append(note);
 }catch(e){holder.textContent='3D를 불러오지 못했습니다. 인터넷 연결과 WebGL 지원을 확인하세요. 계산과 다른 화면은 계속 사용할 수 있습니다.';console.warn('3D unavailable',e)}return dispose;
}
